networks:
  default:
    external: true
    name: cvdp-bridge-cid003_subset_20-a520e676
services:
  pytest:
    command: pytest -s -o cache_dir=/rundir/harness/.cache /src/test_runner.py -v
    env_file: ./src/.env
    image: nvidia/cvdp-sim:v1.0.0
    volumes:
    - ./src/:/src/:ro
    working_dir: /code/rundir
