networks:
  default:
    external: true
    name: cvdp-bridge-subset-a364bd4f
services:
  direct:
    command: pytest -s --log-cli-level=INFO -o cache_dir=/rundir/harness/.cache /src/test_runner.py
      -v
    env_file: ./src/.env
    image: nvidia/cvdp-sim:v1.0.0
    volumes:
    - ./src/:/src/:ro
