networks:
  default:
    external: true
    name: cvdp-bridge-cid003_subset_20-a520e676
services:
  direct:
    build: .
    command: pytest -o cache_dir=/code/rundir/.cache /src/test_runner.py -v
    env_file: ./src/.env
    volumes:
    - ./src/:/src/:ro
    working_dir: /code/rundir
